---
version: 2
build:
  os: "ubuntu-24.04"
  tools:
    nodejs: "22"
    python: "3.14"
    ruby: "3.3"
    rust: "1.91"
  apt_packages:
    - doxygen
    - graphviz
  commands:
    - npm ci --ignore-scripts
    - npm run build
    - python -m pip install 'lizardbyte-dockle[all] @ https://github.com/LizardByte/dockle/releases/download/v2026.918.203650/lizardbyte_dockle-2026.918.203650-py3-none-any.whl'
    - env PYTHONPATH=third-party/dockle/src python -m dockle check
    - env PYTHONPATH=third-party/dockle/src python -m dockle build
    - 'echo "baseurl: projects/shared-web/$READTHEDOCS_VERSION"/jekyll >> ./examples/jekyll/_config.yml'
    - cd examples/jekyll && npm ci
    - cd examples/jekyll && npm run build
    - mkdir -p "${READTHEDOCS_OUTPUT}html/"
    - cp -r _site/. "${READTHEDOCS_OUTPUT}html/"

submodules:
  include: all
  recursive: true
