# Sonar project analysis properties overrides
# Automatic analysis ignores this file and uses .sonarcloud.properties instead.

sonar.projectKey=LizardByte_shared-web

sonar.exclusions=third-party/**
sonar.test.exclusions=third-party/**
