# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "4.4.1"
gem "jekyll-paginate", "1.1.0"
gem "jekyll-remote-theme", "0.5.1"
gem "jekyll-sitemap", "1.4.0"
gem "kramdown", "2.5.2"
gem "kramdown-parser-gfm", "1.1.0"
gem "webrick", "1.9.2"

gemspec
